### ISSUE TITLE
How to add role assignments?

### ISSUE THREAD

**Issue by oxisto** [protegeproject/webprotege-authorization-service#4]
I am currently trying to run the microservice protege using the docker compose file. I finally got everything set up after fixing some issues with keycloak, etc. I even managed to create a user in key cloak and successfully log in.

However, it seems that the user is not equipped with any (built-in) roles and I struggle to give him any. I debugged my way into the mongo DB and the role assignments collection and was trying to give my "test" user the project creator role.

```
webprotege> db.RoleAssignments.insert({"username": "test", "assignedRoles":["ProjectCreator"], "roleClosure": [], "actionClosure": []})
```

But that does not seem to work, I can still not see the "create project" button.

Am I on the right direction? It would be fantastic if the docker compose example would have already an existing user :(

**Comment by matthewhorridge** [comment]
At the moment, a way around this, is to sign into keycloak at `http://webprotege-local.edu/auth/` and add the "ProjectCreator" client role (Users > {userName} > Role Mappings > Client Roles (select webprotege) and then add `ProjectCreator`

**Comment by oxisto** [comment]
> At the moment, a way around this, is to sign into keycloak at `http://webprotege-local.edu/auth/` and add the "ProjectCreator" client role (Users > {userName} > Role Mappings > Client Roles (select webprotege) and then add `ProjectCreator`

aaah! that worked :) I was looking for roles but did not have a look at the client roles.
